# Generated by Django 3.2.3 on 2021-05-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_advertisement_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='compamy',
            new_name='company',
        ),
    ]
